#ifndef FIXED_STAR_D3D11_HPP_
#define FIXED_STAR_D3D11_HPP_

#include "com.hpp"
#include <specstrings.h>
#include <d3d11.h>
#include <d3d11shader.h>
#include <d3d11sdklayers.h>

#ifndef MSC_VER

namespace fixed_star {

	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Asynchronous )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11BlendState )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11CommandList )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Counter )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11DepthStencilState )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Device )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11DeviceChild )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11DeviceContext )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11InputLayout )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Predicate )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Query )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11RasterizerState )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11SamplerState )

	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Debug )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11InfoQueue )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11SwitchToRef )

	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Buffer )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11DepthStencilView )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11RenderTargetView )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Resource )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11ShaderResourceView )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Texture1D )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Texture2D )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11Texture3D )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11UnorderedAccessView )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11View )

	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11ClassInstance )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11ClassLinkage )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11ComputeShader )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11DomainShader )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11GeometryShader )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11HullShader )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11PixelShader )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11ShaderReflection )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11ShaderReflectionConstantBuffer )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11ShaderReflectionType )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D11ShaderReflectionVariable )
	
} // namespace fixed_star

#endif

#endif // FIXED_STAR_D3D11_HPP_
