#ifndef FIXED_STAR_D3D10_HPP_
#define FIXED_STAR_D3D10_HPP_

#include "com.hpp"
#include <d3d10.h>

#ifndef MSC_VER

namespace fixed_star {

	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Asynchronous )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10BlendState )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Blob )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Counter )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Debug )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10DepthStencilState )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Device )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10DeviceChild )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Include )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10InfoQueue )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10InputLayout )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Multithread )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Predicate )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Query )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10RasterizerState )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10SamplerState )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10StateBlock )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10SwitchToRef )

	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Buffer )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10DepthStencilView )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10RenderTargetView )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Resource )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10ShaderResourceView )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Texture1D )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Texture2D )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Texture3D )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10View )

	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10GeometryShader )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10PixelShader )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10ShaderReflection )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10ShaderReflectionConstantBuffer )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10ShaderReflectionType )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10ShaderReflectionVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10VertexShader )

	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10Effect )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectBlendVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectConstantBuffer )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectDepthStencilVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectDepthStencilViewVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectMatrixVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectPass )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectPool )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectRasterizerVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectRenderTargetViewVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectSamplerVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectScalarVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectShaderResourceVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectShaderVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectStringVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectTechnique )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectType )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectVariable )
	FIXED_STAR_UUIDOF_SPEC_IID( ID3D10EffectVectorVariable )
	
} // namespace fixed_star

#endif

#endif // FIXED_STAR_D3D10_HPP_
