#ifndef FIXED_STAR_DXGI_HPP_
#define FIXED_STAR_DXGI_HPP_

#include "com.hpp"
#include <dxgi.h>

#ifndef MSC_VER

namespace fixed_star {

	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIAdapter )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIAdapter1 )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIDevice )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIDevice1 )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIDeviceSubObject )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIFactory )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIFactory1 )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIKeyedMutex )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIObject )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIOutput )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGIResource )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGISurface )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGISurface1 )
	FIXED_STAR_UUIDOF_SPEC_IID( IDXGISwapChain )
	
} // namespace fixed_star

#endif

#endif // FIXED_STAR_DXGI_HPP_
